version: 2.1

jobs:
  test:
    parameters:
      ruby-version:
        type: string
      gemfile:
        type: string
    docker:
      - image: 'ruby:<< parameters.ruby-version >>'
    environment:
      BUNDLE_GEMFILE: << parameters.gemfile >>
    steps:
      - checkout
      - run: gem install bundler -v '1.17'
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Run Specs
          command:
            bundle exec rspec

workflows:
  test-suite:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-version:
                - '2.4'
                - '2.5'
                - '2.6'
                - '2.7'
                - '3.0'
                - '3.1'
                - '3.2'
              gemfile:
                - gemfiles/active_record_4.2.gemfile
                - gemfiles/active_record_5.0.gemfile
                - gemfiles/active_record_5.1.gemfile
                - gemfiles/active_record_5.2.gemfile
                - gemfiles/active_record_6.0.gemfile
                - gemfiles/active_record_6.1.gemfile
                - gemfiles/active_record_7.0.gemfile
            exclude:
            - gemfile: gemfiles/active_record_7.0.gemfile
              ruby-version: '2.4'
            - gemfile: gemfiles/active_record_7.0.gemfile
              ruby-version: '2.5'
            - gemfile: gemfiles/active_record_7.0.gemfile
              ruby-version: '2.6'
            - gemfile: gemfiles/active_record_6.1.gemfile
              ruby-version: '2.4'
            - gemfile: gemfiles/active_record_6.1.gemfile
              ruby-version: '3.2'
            - gemfile: gemfiles/active_record_6.0.gemfile
              ruby-version: '2.4'
            - gemfile: gemfiles/active_record_6.0.gemfile
              ruby-version: '3.2'
            - gemfile: gemfiles/active_record_5.2.gemfile
              ruby-version: '3.0'
            - gemfile: gemfiles/active_record_5.2.gemfile
              ruby-version: '3.1'
            - gemfile: gemfiles/active_record_5.2.gemfile
              ruby-version: '3.2'
            - gemfile: gemfiles/active_record_5.1.gemfile
              ruby-version: '3.0'
            - gemfile: gemfiles/active_record_5.1.gemfile
              ruby-version: '3.1'
            - gemfile: gemfiles/active_record_5.1.gemfile
              ruby-version: '3.2'
            - gemfile: gemfiles/active_record_5.0.gemfile
              ruby-version: '3.0'
            - gemfile: gemfiles/active_record_5.0.gemfile
              ruby-version: '3.1'
            - gemfile: gemfiles/active_record_5.0.gemfile
              ruby-version: '3.2'
            - gemfile: gemfiles/active_record_4.2.gemfile
              ruby-version: '3.0'
            - gemfile: gemfiles/active_record_4.2.gemfile
              ruby-version: '3.1'
            - gemfile: gemfiles/active_record_4.2.gemfile
              ruby-version: '2.7'
            - gemfile: gemfiles/active_record_4.2.gemfile
              ruby-version: '3.2'
